### ISSUE TITLE
bsdtar not available on CentOS 6

### ISSUE THREAD

**Issue by smiller171** [andrewrothstein/ansible-unarchive-deps#1]

**Comment by andrewrothstein** [comment]
wasn't planning on supporting EL 6. happy to accept a pull request if you care about EL 6.

**Comment by smiller171** [comment]
I'm not sure I understand the purpose of having both tar and bsdtar. for my use I forked and removed bsdtar from this list. I can submit that PR if it would be acceptable for your purposes.

**Comment by andrewrothstein** [comment]
sure. I'd accept that PR.
