### ISSUE TITLE
Playbook mixing environments when running on Windows WSL 2.0.

### ISSUE THREAD

**Issue by hugoprudente** [andrewrothstein/ansible-unarchive-deps#14]
When using the WSL2.0 the system should not need to try win_psmodule as it's a based linux distro.

```
ERROR! couldn't resolve module/action 'win_psmodule'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/hugo/.ansible/roles/andrewrothstein.unarchive-deps/tasks/main.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        state: present
    - name: install PowerShell module
      ^ here
on ⛵ k3s (unifi) dev-playbook on  main [!?⇡] on ☁️  (sa-east-1) took 2s
❯ uname -a
Linux DESKTOP-RK1RCAL 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by andrewrothstein** [comment]
I don't think it's trying to use the win_ps module in your situation. It's just complaining that it's not installed. Can you confirm that the community.windows.collection is installed per the documentation?
https://docs.ansible.com/ansible/latest/collections/community/windows/win_psmodule_module.html

**Comment by hugoprudente** [comment]
I'm using inside WSL so the windows collection should not be necessary at all in that case, as I'm a subsystem linux.

From the windows perspective it's 100% normal, but if I try to use the role inside a WSL2.0 it fails trying to use the win_ps that I don't want, as I'm already using a linux subsystem.

At some point 5 months ago this was working, when I setup my playbook to run on my linux and my WSL (windows subsystem linux) box, and now it's not.

**Comment by andrewrothstein** [comment]
this role references the win_psmodule module so even if u only targeting Linux hosts, and it won't be used, the Ansible installation needs the full set of referenced modules and collections installed.

do yourself a favor, install the appropriate collection with `ansible-galaxy collection install community.windows` per the instruction and try to apply the role. if this role looks to be using the win_psmodule when u apply it, please open a separate issue and we can debug.

thanks, Drew

**Comment by hugoprudente** [comment]
I'm running inside a linux subsystem, why should I need `ansible-galaxy collection install community.windows ` inside a linux box? 

If I'm trying to configure the subsystem in linux (similar to a vm) and not my windows box itself. 

This role is invoked by the ` andrewrothstein.terraform` that should be able to know if it's runing on whatever emulated system I'm trying to as the WSL (windows linux subsystem) doesn't have PS module or whatever as it's not required.

The role works fine on 
* windows
* linux

but when I'm trying to use the WSL that is the linux subsystem inside of windows it fails as it doesn't handle it well, what looks like a bug and not a feature.

**Comment by rojspencer** [comment]
I ran into this also and looks like a bug in ansible itself.

I do not have community.windows installed on my MacBook yet it runs fine.  Same version of role in an ansible runner and the error of missing ps_module occurs.
