### ISSUE TITLE
Packages are installed in serial

### ISSUE THREAD

**Issue by liamdawson** [andrewrothstein/ansible-unarchive-deps#8]
The `package` module (or at least some of the underlying modules, like `apt` and `dnf`) support parallel installation via passing an array to `name`. When running in a loop, these packages are installed in serial instead, which is a lot slower.

**Comment by andrewrothstein** [comment]
great tip! there's a bunch of places in my roles where I've followed this anti pattern. published the fix as v1.1.0 of the unarchive-deps role. thanks again!
