### ISSUE TITLE
[DEPRECATION WARNING]: Use errors="ignore" instead of skip.

### ISSUE THREAD

**Issue by bbaassssiiee** [andrewrothstein/ansible-unarchive-deps#9]
https://github.com/andrewrothstein/ansible-unarchive-deps/blob/7190eca1aeeb49a4298b2ed1163cd71c80838442/tasks/main.yml#L9

This feature will be removed in version 2.12

**Comment by andrewrothstein** [comment]
tested PRs welcome

**Comment by bbaassssiiee** [comment]
Fix it yourself.
